name: Hello

on: workflow_dispatch

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!"

  second:
    needs: say-hi      
    runs-on: ubuntu-latest
    steps:
      - name: Drugi komunikat
      - run: echo "Hello, GitHub Actions 2!"
